### ISSUE TITLE
Add users

### ISSUE THREAD

**Issue by chriswilson2020** [YunoHost-Apps/ntfy_ynh#31]
### Describe the bug
ntfy is installed for all users but can't login with my credentials when clicking on the tile.  
ntfy user list reports "option auth-file not set; auth is unconfigured for this server"

### Context

- Hardware: Internet Cube with VPN 
- YunoHost version: 11.2.8.2 (stable)
- I have access to my server: Through SSH | through the webadmin | direct access via keyboard / screen | ALL of these
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: 2.8.0~ynh1
- If upgrading, current package version:n/a

### Steps to reproduce
1. installed fresh install from yuno application store
2. Can login with the admin user created during install
3. Can not login with any other user

### Expected behavior
To be able to login or add other users from the web admin or command line

### Logs

<img width="764" alt="Screenshot 2023-12-23 at 16 34 13" src="https://github.com/YunoHost-Apps/ntfy_ynh/assets/73828727/9effe876-9ed8-46a4-b5c2-977d32888d79">

**Comment by chriswilson2020** [comment]
I could add user with the command: ./ntfy user -c server.yml add chris

I am prompted to enter a password and to confirm it by entering again

Suggest a feature to either add all existing users or allow users to be added via the YunoHost app configuration screen?

**Comment by rosbeef** [comment]
i just installed and work on this bug locally.
i understood that ntfy is not using global variable in this car and searching in : 

- /etc/ntfy/ for the server.yml configuration
- /bin/ for the executable
- /var/lib/ntfy for the databases files

So creating the next symbolic links i makes it "patially work"
ln -s /var/www/ntfy/data /var/lib/ntfy
ln -s /var/www/ntfy/ntfy /bin/ntfy
ln -s /var/www/ntfy/ /etc/ntfy

source : https://github.com/binwiederhier/ntfy/issues/421#issuecomment-1264380171

**Comment by l-x** [comment]
1. There is (and will be) no LDAP in https://github.com/binwiederhier/ntfy, so syncing users between Yunohost and ntfy will never happen
2. There is a small wrapper script (`/var/www/<app_name>/ntfy.sh`) for adding users and stuff. This script will use the proper configuration file (and the proper auth database):
```sh
$ sudo -u ntfy /var/www/ntfy/ntfy.sh user list
```

I guess I should simply improve the documentation for this app as it gets more attention :D
