### ISSUE TITLE
Unifiedpush not working with matrix

### ISSUE THREAD

**Issue by rosbeef** [YunoHost-Apps/ntfy_ynh#32]
### Describe the bug

unified push is not working with matrix apps

### Context

- Hardware: *odroid hc1 lxc/d container armbian*
- YunoHost version: 11.2.8.2
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch: 2.8.0-ynh1

### Steps to reproduce

- With the corrected bug from #31 
- Applying the command `sudo -u ntfy ntfy access '*' 'up*' write-only` to authorize anonymous write access for all up* topics.
- Registration an test works from matrix app
- But i never receive notifications

### Expected behavior

Receive notifications

**Comment by l-x** [comment]
See https://github.com/YunoHost-Apps/ntfy_ynh/issues/31#issuecomment-1871101369

Your "fix" with symlinks might be the reason. I advice you to setup a clean instance of nfy_ynh and try again. If the problem persists, it's an upstream's issue.

**Comment by l-x** [comment]
What Matrix App do you use exactly?

**Comment by rosbeef** [comment]
Sorry, back after a year.
With element x f-droid, i can not make ntfy works.
I can login
Troubleshooting notifications return me for the "Test Push loop back" a 403 error

I configure ntfy f-droid with 
- my server as endpoint (https://ntfy.domain,tld)
- my user for all "service URL" corresponding to https://ntfy.domain,tld

I opened element x, selected ntfy as notify app. 
The topic were well created and added to my user.

I stuck on which next step to do to make it works.

**Comment by yekibud** [comment]
Similar issue for me.  @rosbeef do you also get "DNS lookup failed: no results for hostname lookup: ntfy.domain.tld"?  I've tried to add whitelisting to synapse per the unified push troubleshooting docs for matrix and still nothing.
